# Grafana configuration
grafana:
  adminUser: admin
  adminPassword: cTcTgLE62nItyZzp
  service:
    type: LoadBalancer 

# Prometheus server configuration
prometheus:
  server:
    service:
      type: LoadBalancer 

# Optional: disable unnecessary components
alertmanager:
  enabled: false
pushgateway:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
